exclude: '^docs/conf.py'

repos:
# black
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=no']
  - id: flake8
    args: ['--max-line-length=88']  # default of Black
